student/urls.py
from django.urls import path
from .views import student, select_student, not_select_student, edit_student

app_name = "student"

urlpatterns = [
    path("<slug:serial>/", student, name="student"),
    path("select-student/<slug:serial>/", select_student, name="select_student"),
    path(
        "not-select-student/<slug:serial>/",
        not_select_student,
        name="not_select_student",
    ),
    path("edit-student/<slug:serial>/", edit_student, name="edit_student"),
    # path('support-document/<slug:serial>/', support_document, name='support_document'),
]

wbpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("school.urls", namespace="school")),
    path("student/", include("student.urls", namespace="student")),
]

student/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from school.models import Profile

SUBJECT_SHORT_CODE = {
    "00": "Pwr",
    "01": "AS",
    "02": "B(FL)",
    "03": "E(FL)",
    "04": "GUJ(FL)",
    "05": "HIN(FL)",
    "06": "MAL(FL)",
    "07": "MAR(FL)",
    "08": "LU(FL)",
    "09": "TBM(FL)",
    "10": "N(FL)",
    "11": "OY(FL)",
    "12": "GUR(FL)",
    "13": "SAN(FL)",
    "14": "SAD(FL)",
    "15": "TEL(FL)",
    "16": "TAM(FL)",
    "17": "U(FL)",
    "20": "E(SL)",
    "21": "E(SL)",
    "22": "B(SL)",
    "23": "N(SL)",
    "31": "B(A)",
    "32": "E",
    "33": "HIN(A)",
    "34": "N",
    "35": "U",
    "36": "B(B)",
    "37": "S",
    "39": "P.",
    "40": "A",
    "44": "Fr.",
    "47": "HIN(B)",
    "52": "M",
    "54": "PH",
    "55": "CH",
    "56": "BIO",
    "57": "MC",
    "58": "G",
    "60": "LG",
    "61": "PSY",
    "62": "BC",
    "63": "BK",
    "64": "EC",
    "65": "HS",
    "66": "MU V",
    "67": "MU I",
    "70": "SEW",
    "71": "AG",
    "72": "PS",
    "73": "AH",
    "76": "HY",
    "84": "WPS",
    "85": "CA",
    "86": "RStr",
    "87": "SStr",
    "88": "AStr",
    "89": "IT",
    "90": "HStr",
    "91": "Elec",
    "92": "IS",
    "93": "TH",
    "94": "Cons",
    "95": "Aprl",
    "96": "Plmb",
    "97": "BW",
    "98": "Lthr",
    "99": "Agrl",
}

FIRST_LANGUAGE_CODE = {
    "02": "BENGALI",
    "03": "ENGLISH",
    "04": "GUJRATI",
    "05": "HINDI",
    "09": "MODERN TIBETAN",
    "10": "NEPALI",
    "11": "ODIA",
    "12": "GURUMUKHI(PUNJABI)",
    "13": "SANTALI",
    "15": "TELEGU",
    "16": "TAMIL",
    "17": "URDU",
}

SECOND_LANGUAGE_CODE = {"21": "ENGLISH", "22": "BENGALI", "23": "NEPALI"}

OPTIONAL_ELECTIVE_SUBJECTS_DICT = {
    "00": "POWER",
    "31": "BENGALI(A LEVEL)",
    "32": "ENGLISH",
    "33": "HINDI(A LEVEL)",
    "34": "NEPALI",
    "35": "URDU",
    "36": "BENGALI(B LEVEL)",
    "37": "SANSKRIT",
    "39": "PERSIAN",
    "40": "ARABIC",
    "44": "FRENCH",
    "47": "HINDI(B LEVEL)",
    "52": "MATHEMATICS",
    "54": "PHYSICS",
    "55": "CHEMISTRY",
    "56": "BIOLOGY",
    "57": "MECHANICS",
    "58": "GEOGRAPHY",
    "60": "LOGIC",
    "61": "PSYCHOLOGY",
    "62": "BUSINESS METHOD & CORRESPONDENCE",
    "63": "BOOK KEEPING",
    "64": "EL.OF ECONOMICS & CIVICS",
    "65": "HOME SC. AND HOME NURSING",
    "66": "MUSIC VOCAL",
    "67": "MUSIC INSTRUMENTAL",
    "70": "SEWING AND NEEDLE CRAFT",
    "71": "EL.OF AGRL. AND HORTICULTURE",
    "72": "PISCICULTURE",
    "73": "ANIMAL HUSBANDRY /POULTRY FARM",
    "76": "PHYSIOLOGY & HYGIENE",
    "84": "WORK EDUCATION GROUP",
    "85": "COMPUTER APPLICATION",
    "86": "RETAIL SECTOR",
    "87": "SECURITY SECTOR",
    "88": "AUTOMOBILE SECTOR",
    "89": "IT/IT'es SECTOR",
    "90": "HEALTH CARE SECTOR",
    "91": "ELECTRONICS",
    "92": "IRON & STEEL",
    "93": "TOURISM & HOSPITALITY",
    "94": "CONSTRUCTION",
    "95": "APPAREL",
    "96": "PLUMBING",
    "97": "BEAUTY & WELLNESS",
    "98": "LEATHER",
    "99": "AGRICULTURE",
}

RELIGION_DICT = {
    "1": "HINDUISM",
    "2": "ISLAM",
    "3": "CHRISTIANITY",
    "4": "BUDDHISM",
    "5": "SIKHISM",
    "6": "ZORASTRIAN",
    "7": "OTHERS",
}

CASTE_DICT = {
    "": "GENERAL",
    "1": "SCHEDULED CASTE",
    "2": "SCHEDULED TRIBES",
    "3": "OTHER BACKWARD CLASSES",
}

SEX_CHOICES = {"1": "MALE", "2": "FEMALE"}

STATUS_CHOICES = (
    ("", "Pending"),
    ("1", "Selected"),
    ("2", "Not Selected"),
)


def profile_upload_path(instance, filename):
    extension = filename.split(".")[-1]
    path = instance.path_target.split(".")[0].replace("\\", "/")
    return "{0}.{1}".format(path, extension)


class Student(models.Model):
    school = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    school_profile = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    path_target = models.CharField(max_length=20)
    name = models.CharField(max_length=40)
    f_name = models.CharField(
        max_length=40, verbose_name="Father's Name", null=True, blank=True
    )
    m_name = models.CharField(
        max_length=40, verbose_name="Mother's Name", null=True, blank=True
    )
    g_indicator = models.CharField(max_length=1, null=True, blank=True)
    g_name = models.CharField(
        max_length=40, null=True, verbose_name="Guardian's Name", blank=True
    )
    sex = models.CharField(max_length=1, verbose_name="Gender")
    religion = models.CharField(max_length=1)
    caste = models.CharField(max_length=1, null=True, blank=True)
    dob = models.CharField(
        max_length=10, verbose_name="Date of Birth", null=True, blank=True
    )
    fl = models.CharField(max_length=2, verbose_name="First Language")
    sl = models.CharField(max_length=2, verbose_name="Second Language")
    opt = models.CharField(
        max_length=2, null=True, blank=True, verbose_name="Optional Elective"
    )
    serial = models.CharField(max_length=4)
    edited = models.BooleanField(default=False)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, null=True)
    profile_picture = models.FileField(
        upload_to=profile_upload_path, null=True, blank=True
    )
    profile_pic_ind = models.CharField(max_length=1, null=True, blank=True)
    underage_candidate = models.BooleanField(default=False)

    def __str__(self):
        return self.school.username

    def get_absolute_url(self):
        return reverse("student:student", kwargs={"serial": self.serial})

    def get_fl_name(self):
        return FIRST_LANGUAGE_CODE[self.fl]

    def get_sl_name(self):
        return SECOND_LANGUAGE_CODE[self.sl]

    def get_opt_name(self):
        if self.opt:
            return OPTIONAL_ELECTIVE_SUBJECTS_DICT[self.opt]
        return ""

    def get_fl_short_code(self):
        return SUBJECT_SHORT_CODE[self.fl]

    def get_sl_short_code(self):
        return SUBJECT_SHORT_CODE[self.sl]

    def get_opt_el_short_code(self):
        if self.opt:
            return SUBJECT_SHORT_CODE[self.opt]
        return ""

    def get_guardian_name(self):
        if self.g_indicator == "M":
            if self.g_name == "":
                return self.m_name
            elif self.g_name == self.f_name:
                return self.f_name
            else:
                return self.g_name
        else:
            if self.g_name == self.m_name:
                return self.m_name
            elif self.g_name == self.f_name:
                return self.f_name
            elif self.g_name == "":
                return self.f_name
            else:
                return self.g_name

    def get_gender(self):
        return SEX_CHOICES[self.sex]

    def get_caste(self):
        if self.caste:
            return CASTE_DICT[self.caste]
        return "GENERAL"

    def get_religion(self):
        return RELIGION_DICT[self.religion]

    class Meta:
        ordering = ("serial",)

    def save(self, *args, **kwargs):
        self.name = self.name.upper()
        try:
            self.f_name = self.f_name.upper()
        except Exception:
            pass

        try:
            self.m_name = self.m_name.upper()
        except Exception:
            pass

        try:
            self.g_name = self.g_name.upper()
        except Exception:
            pass
        super(Student, self).save(*args, **kwargs)


class SupportDocument(models.Model):
    student = models.OneToOneField(Student, on_delete=models.SET_NULL, null=True)
    document = models.CharField(
        max_length=50,
        help_text="Please mention the supporting document on basis of which the change was made. Ex: admission register / birth certificate / etc",
    )

    def __str__(self):
        return self.student.serial

student/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from datetime import datetime
from .models import Student, SupportDocument
from .forms import StudentForm
from .decorators import can_edit_data
from school.models import Profile


@login_required
@can_edit_data
def student(request, serial):
    try:
        request.user.profile
    except Profile.DoesNotExist:
        return redirect("school:profile")

    student = Student.objects.filter(school=request.user, serial=serial)[0]
    blank_warning = []

    if not student.f_name or student.f_name == "":
        blank_warning.append("Father's Name is BLANK")

    if not student.m_name or student.m_name == "":
        blank_warning.append("Mother's Name is BLANK")

    if (student.f_name == "" or student.f_name is None) and (
        student.g_indicator == "" or student.g_indicator is None
    ):
        if (student.m_name == "" or not student.m_name) and (
            student.f_name == "" or not student.f_name
        ):
            if not student.g_name or student.g_name == "":
                blank_warning.append("Guardian's Name is BLANK")

    if not student.dob or student.dob == "":
        blank_warning.append("Date of Birth is BLANK")

    if student.name == student.f_name:
        blank_warning.append("Candidate Name and Father's Name are SAME")

    if student.name == student.m_name:
        blank_warning.append("Candidate Name and Mother's Name are SAME")

    if (student.m_name == student.f_name) and (student.m_name or student.f_name):
        blank_warning.append("Mother's Name and Father's Name are SAME")

    context = {"student": student, "blank_warning": blank_warning}
    return render(request, "student/student.html", context)


@login_required
@can_edit_data
def select_student(request, serial):
    try:
        request.user.profile
    except Profile.DoesNotExist:
        return redirect("school:profile")

    student = Student.objects.filter(school=request.user, serial=serial)[0]
    dob = student.dob

    extra_warning = ""

    if (not student.f_name and not student.m_name and student.g_name) or (
        student.f_name == "" and student.m_name == "" and student.g_name
    ):
        extra_warning = "Warning! Father's Name and Mother's Name are blank. "

    if (not student.f_name and not student.m_name and not student.g_name) or (
        student.f_name == "" and student.m_name == "" and student.g_name == ""
    ):
        messages.error(
            request,
            f"Student with \"Blank Father's Name, Mother's Name or Guardian's Name\",  {student.name} can not be selected.",
        )
        return redirect(student.get_absolute_url())

    elif not dob or dob == "":
        messages.error(
            request,
            f'Student with "Blank Date of Birth",  {student.name} can not be selected.',
        )
        return redirect(student.get_absolute_url())

    elif datetime.strptime(dob, "%d%m%y") and datetime.strptime(
        dob, "%d%m%y"
    ) > datetime.strptime("311010", "%d%m%y"):
        messages.error(
            request, f"Under-Age Student,  {student.name} can not be selected."
        )
        return redirect(student.get_absolute_url())

    student.status = "1"
    student.save()

    try:
        next_student = Student.objects.filter(
            school=request.user, serial__gt=serial
        ).first()
        messages.success(
            request,
            f"{extra_warning}Student {student.name} has been marked as Selected.",
        )
        return redirect(next_student.get_absolute_url())
    except Exception:
        return redirect("school:student_list")


@login_required
@can_edit_data
def not_select_student(request, serial):
    try:
        request.user.profile
    except Profile.DoesNotExist:
        return redirect("school:profile")

    student = Student.objects.filter(school=request.user, serial=serial)[0]
    extra_warning = ""

    if (not student.f_name and not student.m_name and student.g_name) or (
        student.f_name == "" and student.m_name == "" and student.g_name
    ):
        extra_warning = "Warning! Father's Name and Mother's Name are blank. "

    student.status = "2"
    student.save()

    try:
        next_student = Student.objects.filter(
            school=request.user, serial__gt=serial
        ).first()
        messages.warning(
            request,
            f"{extra_warning}Student {student.name} has been marked as NOT Selected",
        )
        return redirect(next_student.get_absolute_url())
    except Exception:
        return redirect("school:student_list")


@login_required
@can_edit_data
def edit_student(request, serial):
    try:
        request.user.profile
    except Profile.DoesNotExist:
        return redirect("school:profile")

    student = Student.objects.filter(school=request.user, serial=serial)[0]
    student_dict = model_to_dict(
        student, fields=[field.name for field in student._meta.fields]
    )
    student_dict["g_name"] = student.get_guardian_name()
    try:
        student_dict["dob"] = datetime.strptime(student_dict["dob"], "%d%m%y")
    except (ValueError, KeyError, TypeError):
        student_dict["dob"] = ""
    try:
        document = SupportDocument.objects.get(student=student).document
    except SupportDocument.DoesNotExist:
        document = None

    student_dict["document"] = document

    form = StudentForm(initial=student_dict)

    if request.method == "POST":
        form = StudentForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            support_document = form.cleaned_data.get("document")
            edited = form.cleaned_data.get("edited")
            form.cleaned_data.pop("edited")

            s = form.save(commit=False)
            original_profile_picture = Student.objects.get(
                school=request.user, serial=serial
            ).profile_picture
            if original_profile_picture != s.profile_picture:
                if not original_profile_picture:
                    s.profile_pic_ind = "n"
                else:
                    s.profile_pic_ind = "d"

            try:
                dob = form.cleaned_data.get("dob").strftime("%d%m%y")
            except AttributeError:
                dob = None
            s.dob = dob
            if edited == "1":
                s.edited = True

                s_document, s_document_created = SupportDocument.objects.get_or_create(
                    student=student
                )
                s_document.document = support_document
                s_document.save()
            s.save()
            messages.success(
                request,
                f"Information for student {student.name} has been updated. Please SELECT / NOT SELECT the student.",
            )
            return redirect(student.get_absolute_url())

    context = {"form": form, "student": student}
    return render(request, "student/form.html", context)

student/templates/student/form.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
    .list-group-item{
        padding: .15rem 1rem;
    }
    .help_text{
    	color: red;
    	font-weight: bold;
    	text-shadow: 0 0 black;
    	letter-spacing: 0.1px;
    	font-size: 18px;
    	background-color: white;
    	padding-left: 5px;
    }
    .support-document-form{
        display: none;
    }
    input#id_profile_picture{
        cursor: pointer;
        position: absolute;
        top: 0;
        left: 15px;
        right: 15px;
        bottom: 0;
        z-index: 2;
        opacity: 0;
    }
    .blank-image{
        display: block;
        height: 100%;
        background: lightgray;
        border: 1px solid #000;
        position: relative;
    }
    .blank-image-label{
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    .profile_picture{
        position: relative;
    }
    .profile_picture::before{
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        background-color: rgba(0, 0, 0, 0.8);
        opacity: 0;
        transition: .25s ease-in-out all;
    }
    #id_profile_picture:hover + .profile_picture::before{
        opacity: 1;
    }
    .profile_picture img{
        width: 100%;
        height: 257px;
        object-fit: contain;
        object-position: top center;
    }
    .change-image-label{
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        opacity: 0;
        transition: .25s ease-in-out all;
        color: #fff;
    }
    #id_profile_picture:hover + .profile_picture .change-image-label{
        opacity: 1;
    }
</style>
{% endblock %}
{% load i18n %}
{% block content %}
<section class="student bg-info pt-4" style="min-height: calc(100vh - 111px);">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                {{ form.non_field_errors }}
                <div class="row text-left">
                    {% for f in form %}
                    {% if f.errors %}
                    <div class="col-6">
                        <p class="pl-4" style="color:red;">{{ f.label }}</p>
                        {{ f.errors }}
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                <form method="POST" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="edit-form">
                        <input type="hidden" name="school" value="{{ student.school.id }}" />
                        <input type="hidden" name="edited" value="0" id="id_edited" />
                        <div class="row">
                            <div class="col-md-3" style="position: relative;">
                                {{ form.profile_picture }}
                                <div class="profile_picture h-100">
                                    {% if student.profile_picture %}
                                    <img src="{{ student.profile_picture.url }}" />
                                    <span class="change-image-label">Change Image</span>
                                    {% else %}
                                    <span class="blank-image"><span class="blank-image-label">Upload Image</span></span>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="row">
                                    {% for field in form %}
                                    {% if field.name == 'name' or field.name == 'f_name' or field.name == 'm_name' %}
                                    <div class="col-md-12">
                                        <label for="{{ field.auto_id }}">{{ field.label }}</label>
                                        {{ field }}
                                        {% if field.help_text %}<p class="help_text">{{ field.help_text }}</p>{% endif %}
                                    </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                            {% for field in form %}{% if field.name != 'name' and field.name != 'm_name' and field.name != 'f_name' and field.name != 'edited' and field.name != 'document' and field.name != 'profile_picture' and field.name != 'underage_candidate' %}
                            <div class="col-md-3">
                                <label for="{{ field.auto_id }}">{{ field.label }}</label>
                                {{ field }}
                                {% if field.help_text %}<p class="help_text">{{ field.help_text }}</p>{% endif %}
                            </div>
                            {% endif %}
                            {% endfor %}
                            <div class="col-12">
                                <button class="btn btn-warning btn-block edit-form-button" type="button">{% trans "Submit" %}</button>
                            </div>
                        </div>
                    </div>

                    <div class="support-document-form">
                        <div class="row">
                            {% for field in form %}
                            {% if field.name == 'document' %}
                            <div class="col-md-12">
                                {% if field.help_text %}<p class="help_text">{{ field.help_text }}</p>{% endif %}
                                <label for="{{ field.auto_id }}">{{ field.label }}</label>
                                {{ field }}
                            </div>
                            {% endif %}
                            {% endfor %}
                            <div class="col-12">
                                <button class="btn btn-warning btn-block" type="submit">{% trans "Submit" %}</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
$(document).ready(function() {
    $('#id_profile_picture').on("change", function(){
        console.log($(this))
    })
    $name = $('#id_name').val();
    $originalForm = $("form :input[name!=sex][name!=fl][name!=sl][name!=opt][name!=religion]").serialize();
    $edited = $('#id_edited');
    $editForm = $(".edit-form");
    $supportDocumentForm = $(".support-document-form");
    $supportDocument = $('#id_document');

    $('.edit-form-button').click(function() {
        $newForm = $("form :input[name!=sex][name!=fl][name!=sl][name!=opt][name!=religion]").serialize();

        if ($name !== $('#id_name').val()){
            $('#id_name').removeAttr("required");
        };

        if ($newForm !== $originalForm) {
            $edited.val("1");
	        $editForm.hide();
            $supportDocument.attr('required', '');
            $supportDocumentForm.show();
        } else {
            $('form').submit();
        };

    });
});

window.addEventListener("pageshow", function(event) {
    var historyTraversal = event.persisted ||
        (typeof window.performance != "undefined" &&
            window.performance.navigation.type === 2);
    if (historyTraversal) {
        // Handle page restore.
        window.location.reload();
    }
});

$('input').on('keypress', function(event) {
    var regex = new RegExp("^[a-zA-Z ]+$");
    var key = String.fromCharCode(!event.charCode ? event.which : event.charCode);
    if (!regex.test(key)) {
        event.preventDefault();
        return false;
    }
});
</script>
{% endblock %}

student/templates/student/student.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block style %}
<style>
    .warning-box li {
        font-size: 15px;
        font-weight: bold;
        letter-spacing: 0.5px;
    }
</style>
{% endblock %}
{% block content %}
<section class="py-2">
    <div class="container">
        <h2>Student Details</h2>
        <div class="p-2" style="background-color: #ededed;">
            <div class="row">
                <div class="col-md-9 pl-4">
                    <div class="row">
                        <div class="col-md-3">
                            <p><strong>Student Name</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{{ student.name }}</p>
                        </div>
                        <div class="col-md-3">
                            <p><strong>Father's Name</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{{ student.f_name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <p><strong>Mother' Name</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{{ student.m_name }}</p>
                        </div>
                        <div class="col-md-3">
                            <p><strong>Guardian's Name</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{{ student.get_guardian_name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <p><strong>Date of Birth</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{{ student.dob|date_format|date }}</p>
                        </div>
                        <div class="col-md-3">
                            <p><strong>Gender</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{{ student.get_gender }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <p><strong>Caste</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{{ student.get_caste }}</p>
                        </div>
                        <div class="col-md-3">
                            <p><strong>Religion</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{{ student.get_religion }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <p><strong>First Language</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{{ student.get_fl_name }}</p>
                        </div>
                        <div class="col-md-3">
                            <p><strong>Second Language</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{{ student.get_sl_name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <p><strong>Optional Elective</strong>:</p>
                        </div>
                        <div class="col-md-3">
                            <p>{% if student.opt %}{{ student.get_opt_name }}{% else %}NONE{% endif %}</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-md-12">
                            <p class="mb-2 text-center"><strong>Profile Picture</strong></p>
                            {% if student.profile_picture %}
                            <img src="{{ student.profile_picture.url }}"
                                class="img-fluid w-75 d-block mx-auto text-center" />
                            {% else %}
                            <p class="text-bold text-danger"><strong>PICTURE MISSING/DAMAGED. KINDLY UPLOAD THE
                                    PICTURE</strong>
                            </p>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-4"><a href="{% url 'student:select_student' serial=student.serial %}"
                    class="btn btn-success d-block">Verified and Selected</a></div>
            <div class="col-md-4"><a href="{% url 'student:not_select_student' serial=student.serial %}"
                    class="btn btn-warning d-block">Verified and Not Selected</a></div>
            <div class="col-md-4"><a href="{% url 'student:edit_student' serial=student.serial %}"
                    class="btn btn-primary d-block">Edit</a></div>
        </div>
        {% if blank_warning|length > 0 %}
        <div class="warning-box bg-info mt-3 py-3">
            <h5 class="pl-4 mb-3">Important Points to Consider:</h5>
            <ul>
                {% for bw in blank_warning %}<li>{{ bw }}</li>{% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}