school/urls.py
from django.urls import path
from .views import (
    index,
    login_view,
    logout_view,
    student_list,
    submit_final_data,
    pdf_report,
    profile,
    reset_password,
    instructions,
    school_status,
)

app_name = "school"

urlpatterns = [
    path("", index, name="index"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("students/", student_list, name="student_list"),
    path("submit-data/", submit_final_data, name="submit_final_data"),
    path("pdf-report/", pdf_report, name="pdf_report"),
    path("profile/", profile, name="profile"),
    path("reset-password/", reset_password, name="reset_password"),
    path("instructions/", instructions, name="instructions"),
    path("data-summary/", school_status, name="school_status"),
]

wbpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("school.urls", namespace="school")),
    path("student/", include("student.urls", namespace="student")),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>W.B.B.S.E.</title>
    <style>
    .errorlist {
        padding-left: 15px;
        color: red;
        text-shadow: 0 0 black;
    }
    .alert-error{
        background-color: white;
        color: red;
        font-weight: bold;
    }
    </style>
    {% block style %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-dark fixed-top">
        <a href="{% url 'school:index' %}" class="navbar-brand">
            <img src="{% static 'logo.png' %}" height="85" alt="CoolBrand">
            <span class="d-inline ml-2 my-auto" style="font-size:36px;color:#fff;letter-spacing: 1.2px;vertical-align:middle;">W.B.B.S.E.</span>
        </a>
        <button class=" navbar-toggler bg-light" data-toggle="collapse" data-target="#nav"><span class="navbar-toggler-icon"></span></button>
        <div class=" collapse navbar-collapse justify-content-between" id="nav">
            <ul class="navbar-nav ml-auto">
                <li class='nav-item'><a class='nav-link text-light text-uppercase font-weight-bold px-3' href="{% url 'school:index' %}">Home</a></li>
                <li class='nav-item'><a class='nav-link text-light text-uppercase font-weight-bold px-3' href="{% url 'school:student_list' %}">Students List</a></li>
                <li class='nav-item'><a class='nav-link text-light text-uppercase font-weight-bold px-3' href="{% url 'school:instructions' %}">Instructions</a></li>
                {% comment %} <li class='nav-item'><a target="_blank" class='nav-link text-light text-uppercase font-weight-bold px-3' href="{% static 'schedule/EMUC34.pdf' %}">EMU/C/34</a></li> {% endcomment %}
                {% comment %} <li class='nav-item dropdown'>
                    <a class='nav-link dropdown-toggle text-light text-uppercase font-weight-bold px-3' id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Download Challan</a>
                    <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropwdown-item nav-link text-light text-uppercase font-weight-bold" href="{% static 'challan/Challan_002.pdf' %}" target="_blank">State Bank of India</a>
                        <a class="dropwdown-item nav-link text-light text-uppercase font-weight-bold" href="{% static 'challan/Challan_001.pdf' %}" target="_blank">Other than SBI</a>
                    </div>
                </li> {% endcomment %}
                {% if request.user.is_authenticated %}
                <li class='nav-item'><a class='nav-link text-light text-uppercase font-weight-bold px-3' href="{% url 'school:logout' %}">Logout</a></li>
                {% else %}
                <li class='nav-item'><a class='nav-link text-light text-uppercase font-weight-bold px-3' href="{% url 'school:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <section class="bg-info" style="margin-top: 111px">
    {% if messages %}
    {% for message in messages %}
    <div class="alert mb-0 alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    </section>
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>
</html>