school/urls.py
from django.urls import path
from .views import (
    index,
    login_view,
    logout_view,
    student_list,
    submit_final_data,
    pdf_report,
    profile,
    reset_password,
    instructions,
    school_status,
)

app_name = "school"

urlpatterns = [
    path("", index, name="index"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("students/", student_list, name="student_list"),
    path("submit-data/", submit_final_data, name="submit_final_data"),
    path("pdf-report/", pdf_report, name="pdf_report"),
    path("profile/", profile, name="profile"),
    path("reset-password/", reset_password, name="reset_password"),
    path("instructions/", instructions, name="instructions"),
    path("data-summary/", school_status, name="school_status"),
]

wbpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("school.urls", namespace="school")),
    path("student/", include("student.urls", namespace="student")),
]

school/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User


class Profile(models.Model):
    school = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    headmaster_name = models.CharField(max_length=50)
    headmaster_email = models.EmailField(max_length=70)
    headmaster_phone = models.BigIntegerField(
        validators=[MinValueValidator(1000000000), MaxValueValidator(9999999999)]
    )
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    complete = models.BooleanField(default=False)
    password_changed = models.BooleanField(default=False)
    verification_name = models.CharField(max_length=50, null=True)
    final_submitted_at = models.DateTimeField(null=True)

    def __str__(self):
        return self.school.username

    def save(self, *args, **kwargs):
        if self.verification_name:
            self.verification_name = self.verification_name.upper()
        super(Profile, self).save(*args, **kwargs)

student/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from school.models import Profile

SUBJECT_SHORT_CODE = {
    "00": "Pwr",
    "01": "AS",
    "02": "B(FL)",
    "03": "E(FL)",
    "04": "GUJ(FL)",
    "05": "HIN(FL)",
    "06": "MAL(FL)",
    "07": "MAR(FL)",
    "08": "LU(FL)",
    "09": "TBM(FL)",
    "10": "N(FL)",
    "11": "OY(FL)",
    "12": "GUR(FL)",
    "13": "SAN(FL)",
    "14": "SAD(FL)",
    "15": "TEL(FL)",
    "16": "TAM(FL)",
    "17": "U(FL)",
    "20": "E(SL)",
    "21": "E(SL)",
    "22": "B(SL)",
    "23": "N(SL)",
    "31": "B(A)",
    "32": "E",
    "33": "HIN(A)",
    "34": "N",
    "35": "U",
    "36": "B(B)",
    "37": "S",
    "39": "P.",
    "40": "A",
    "44": "Fr.",
    "47": "HIN(B)",
    "52": "M",
    "54": "PH",
    "55": "CH",
    "56": "BIO",
    "57": "MC",
    "58": "G",
    "60": "LG",
    "61": "PSY",
    "62": "BC",
    "63": "BK",
    "64": "EC",
    "65": "HS",
    "66": "MU V",
    "67": "MU I",
    "70": "SEW",
    "71": "AG",
    "72": "PS",
    "73": "AH",
    "76": "HY",
    "84": "WPS",
    "85": "CA",
    "86": "RStr",
    "87": "SStr",
    "88": "AStr",
    "89": "IT",
    "90": "HStr",
    "91": "Elec",
    "92": "IS",
    "93": "TH",
    "94": "Cons",
    "95": "Aprl",
    "96": "Plmb",
    "97": "BW",
    "98": "Lthr",
    "99": "Agrl",
}

FIRST_LANGUAGE_CODE = {
    "02": "BENGALI",
    "03": "ENGLISH",
    "04": "GUJRATI",
    "05": "HINDI",
    "09": "MODERN TIBETAN",
    "10": "NEPALI",
    "11": "ODIA",
    "12": "GURUMUKHI(PUNJABI)",
    "13": "SANTALI",
    "15": "TELEGU",
    "16": "TAMIL",
    "17": "URDU",
}

SECOND_LANGUAGE_CODE = {"21": "ENGLISH", "22": "BENGALI", "23": "NEPALI"}

OPTIONAL_ELECTIVE_SUBJECTS_DICT = {
    "00": "POWER",
    "31": "BENGALI(A LEVEL)",
    "32": "ENGLISH",
    "33": "HINDI(A LEVEL)",
    "34": "NEPALI",
    "35": "URDU",
    "36": "BENGALI(B LEVEL)",
    "37": "SANSKRIT",
    "39": "PERSIAN",
    "40": "ARABIC",
    "44": "FRENCH",
    "47": "HINDI(B LEVEL)",
    "52": "MATHEMATICS",
    "54": "PHYSICS",
    "55": "CHEMISTRY",
    "56": "BIOLOGY",
    "57": "MECHANICS",
    "58": "GEOGRAPHY",
    "60": "LOGIC",
    "61": "PSYCHOLOGY",
    "62": "BUSINESS METHOD & CORRESPONDENCE",
    "63": "BOOK KEEPING",
    "64": "EL.OF ECONOMICS & CIVICS",
    "65": "HOME SC. AND HOME NURSING",
    "66": "MUSIC VOCAL",
    "67": "MUSIC INSTRUMENTAL",
    "70": "SEWING AND NEEDLE CRAFT",
    "71": "EL.OF AGRL. AND HORTICULTURE",
    "72": "PISCICULTURE",
    "73": "ANIMAL HUSBANDRY /POULTRY FARM",
    "76": "PHYSIOLOGY & HYGIENE",
    "84": "WORK EDUCATION GROUP",
    "85": "COMPUTER APPLICATION",
    "86": "RETAIL SECTOR",
    "87": "SECURITY SECTOR",
    "88": "AUTOMOBILE SECTOR",
    "89": "IT/IT'es SECTOR",
    "90": "HEALTH CARE SECTOR",
    "91": "ELECTRONICS",
    "92": "IRON & STEEL",
    "93": "TOURISM & HOSPITALITY",
    "94": "CONSTRUCTION",
    "95": "APPAREL",
    "96": "PLUMBING",
    "97": "BEAUTY & WELLNESS",
    "98": "LEATHER",
    "99": "AGRICULTURE",
}

RELIGION_DICT = {
    "1": "HINDUISM",
    "2": "ISLAM",
    "3": "CHRISTIANITY",
    "4": "BUDDHISM",
    "5": "SIKHISM",
    "6": "ZORASTRIAN",
    "7": "OTHERS",
}

CASTE_DICT = {
    "": "GENERAL",
    "1": "SCHEDULED CASTE",
    "2": "SCHEDULED TRIBES",
    "3": "OTHER BACKWARD CLASSES",
}

SEX_CHOICES = {"1": "MALE", "2": "FEMALE"}

STATUS_CHOICES = (
    ("", "Pending"),
    ("1", "Selected"),
    ("2", "Not Selected"),
)


def profile_upload_path(instance, filename):
    extension = filename.split(".")[-1]
    path = instance.path_target.split(".")[0].replace("\\", "/")
    return "{0}.{1}".format(path, extension)


class Student(models.Model):
    school = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    school_profile = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    path_target = models.CharField(max_length=20)
    name = models.CharField(max_length=40)
    f_name = models.CharField(
        max_length=40, verbose_name="Father's Name", null=True, blank=True
    )
    m_name = models.CharField(
        max_length=40, verbose_name="Mother's Name", null=True, blank=True
    )
    g_indicator = models.CharField(max_length=1, null=True, blank=True)
    g_name = models.CharField(
        max_length=40, null=True, verbose_name="Guardian's Name", blank=True
    )
    sex = models.CharField(max_length=1, verbose_name="Gender")
    religion = models.CharField(max_length=1)
    caste = models.CharField(max_length=1, null=True, blank=True)
    dob = models.CharField(
        max_length=10, verbose_name="Date of Birth", null=True, blank=True
    )
    fl = models.CharField(max_length=2, verbose_name="First Language")
    sl = models.CharField(max_length=2, verbose_name="Second Language")
    opt = models.CharField(
        max_length=2, null=True, blank=True, verbose_name="Optional Elective"
    )
    serial = models.CharField(max_length=4)
    edited = models.BooleanField(default=False)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, null=True)
    profile_picture = models.FileField(
        upload_to=profile_upload_path, null=True, blank=True
    )
    profile_pic_ind = models.CharField(max_length=1, null=True, blank=True)
    underage_candidate = models.BooleanField(default=False)

    def __str__(self):
        return self.school.username

    def get_absolute_url(self):
        return reverse("student:student", kwargs={"serial": self.serial})

    def get_fl_name(self):
        return FIRST_LANGUAGE_CODE[self.fl]

    def get_sl_name(self):
        return SECOND_LANGUAGE_CODE[self.sl]

    def get_opt_name(self):
        if self.opt:
            return OPTIONAL_ELECTIVE_SUBJECTS_DICT[self.opt]
        return ""

    def get_fl_short_code(self):
        return SUBJECT_SHORT_CODE[self.fl]

    def get_sl_short_code(self):
        return SUBJECT_SHORT_CODE[self.sl]

    def get_opt_el_short_code(self):
        if self.opt:
            return SUBJECT_SHORT_CODE[self.opt]
        return ""

    def get_guardian_name(self):
        if self.g_indicator == "M":
            if self.g_name == "":
                return self.m_name
            elif self.g_name == self.f_name:
                return self.f_name
            else:
                return self.g_name
        else:
            if self.g_name == self.m_name:
                return self.m_name
            elif self.g_name == self.f_name:
                return self.f_name
            elif self.g_name == "":
                return self.f_name
            else:
                return self.g_name

    def get_gender(self):
        return SEX_CHOICES[self.sex]

    def get_caste(self):
        if self.caste:
            return CASTE_DICT[self.caste]
        return "GENERAL"

    def get_religion(self):
        return RELIGION_DICT[self.religion]

    class Meta:
        ordering = ("serial",)

    def save(self, *args, **kwargs):
        self.name = self.name.upper()
        try:
            self.f_name = self.f_name.upper()
        except Exception:
            pass

        try:
            self.m_name = self.m_name.upper()
        except Exception:
            pass

        try:
            self.g_name = self.g_name.upper()
        except Exception:
            pass
        super(Student, self).save(*args, **kwargs)


class SupportDocument(models.Model):
    student = models.OneToOneField(Student, on_delete=models.SET_NULL, null=True)
    document = models.CharField(
        max_length=50,
        help_text="Please mention the supporting document on basis of which the change was made. Ex: admission register / birth certificate / etc",
    )

    def __str__(self):
        return self.student.serial

school/forms.py
from django import forms
from django.contrib.auth import authenticate
from .models import Profile
from django.contrib.auth.forms import PasswordChangeForm


class UsersLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UsersLoginForm, self).__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update(
            {"class": "form-control", "name": "username"}
        )
        self.fields["password"].widget.attrs.update(
            {"class": "form-control", "name": "password"}
        )

    def clean(self, *args, **keyargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError(
                    "Invalid Credentials! Please check username and password again."
                )
            if not user.is_active:
                raise forms.ValidationError("User is no longer active")

        return super(UsersLoginForm, self).clean(*args, **keyargs)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ["school", "complete", "password_changed", "verification_name", "final_submitted_at"]

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        self.fields["headmaster_name"].label = "Name of the Head of Institution"
        self.fields["headmaster_phone"].label = "Mobile Number"
        self.fields["headmaster_email"].label = "E-mail Address"

        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})


class PasswordResetForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})

school/templates/school/index.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<style>
    p {
        font-size: 24px;
        color: #020073;
        font-weight: bold;
    }

    .scroll-left {
        height: 35px;
        overflow: hidden;
        position: relative;
        background: #ff0000e6;
        border: 1px solid #ff0000e6;
    }

    .scroll-left span {
        position: absolute;
        width: 100%;
        height: 100%;
        margin: 0;
        text-transform: uppercase;
        /*line-height: 50px;*/
        text-align: center;
        /* Starting position */
        transform: translateX(100%);
        /* Apply animation to this element */
        animation: scroll-left 18s linear infinite;
        letter-spacing: 0.5px;
        font-size: 20px;
        color: #020073;
    }

    /* Move it (define the animation) */
    @keyframes scroll-left {
        0% {
            transform: translateX(100%);
        }

        100% {
            transform: translateX(-100%);
        }
    }
</style>
{% endblock %}
{% block content %}
<!-- banner -->
<section class="bg-info">
    {% comment %} <div class="scroll-left">
        <span>
            The last date of submission of "Final Data" is <b>17/8/2024</b>
        </span>
    </div> {% endcomment %}
    <div class="container-fluid">
        <div class="row justify-content-center align-items-center" style="min-height: calc(100vh - 111px);">
            <div class=" col-md-12 text-center">
                <h2 class=" display-4 text-capitalize">
                    <span class=" text-warning">West Bengal Board Of Secondary Education </span><br>
                    <span class=" text-white font-weight-bold">Registration Data Online Verification Portal</span>
                </h2>
                <p>Please visit the <a style="color: inherit;" href="{% url 'school:instructions' %}">instructions</a>
                    tab for detailed instruction on how to use the website.</p>
                <br><br>
                {% if not request.user.is_authenticated %}<a href="{% url 'school:login' %}"
                    class=" btn btn-warning">Login Page</a>{% endif %}
                <a href="{% url 'school:student_list' %}" class=" btn btn-success">Student List</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

school/templates/school/pdf-report.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load custom_filters %}
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ school.username }} Report</title>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');
	 	body{
	 		margin: 0;
			padding: 0;
	 	}
	 	*{
	 		font-family: 'Roboto', sans-serif;
	 		letter-spacing: 0.5px;
	 	}
		tr {
			page-break-inside: avoid !important;
		}
		thead {
			display: table-header-group !important;
		}
		tfoot {
			display: table-footer-group !important;
		}
	 	tbody tr td{
	 		padding: 8px 2px;
	 		font-size: 14px;
	 	}
	 	th{
	 		padding: 5px 2px;
	 	}
	 	table{
	 		width: 100%;
	 		margin-top: 10px;
	 	}
		table, th, td {
			border: 1px solid black;
			border-collapse: collapse;
			text-align: center;
		}
	 	.logo{
	 		display: inline-block;
			vertical-align: middle;
	 	}
	 	.heading{
			display: inline-block;
			vertical-align: middle;
			margin-left: 15px;
	 	}
	 	.heading h2{
	 		margin: 0;
	 	}
	 	.logo img{
	 		width: 75px;
	 	}
	 	.white{
	 		background-color: floralwhite;
	 	}
	 	.gray{
	 		background-color: rgba(0, 0, 0, 0.3);
	 	}
	 	.declaration{
	 		text-align: left !important;
	 		padding-bottom: 50px;
	 	}
	 	p.school-info{
	 		margin-top: 20px;
	 	}
	 	.bottom-box{
	 		text-align: right;
	 		padding-top: 50px;
	 	}
	 	.bottom-box p{
	 		margin: 0;
	 	}
		.report-date {
			text-align: center;
			padding-top: 50px;
		}
		.report-date p {
			margin: 0;
		}
	 	.verified_declaration{
			font-size: 18px;
			border-bottom: 1px solid #000;
			padding-bottom: 2px;
		}
		.verified_declaration span{
			font-weight: bold;
			padding-left: 2px;
		}
	 	.declaration_line{
	 		padding-top: 10px;
	 	}
		.signature{
			border-top: 1px solid #000;
			display: inline-block;
			padding-top: 2px;
		}
		td img{
			width: 35px;
			height: auto;
		}
	</style>
</head>
<body>
	<div class="logo">
		{% comment %} <img src="{{ domain }}{% static 'logo.png' %}" /> {% endcomment %}
	</div>
	<div class="heading">
		<h2>Final Report of Data Verification of Registration for Class(IX) Year 2023</h2>
	</div>
	<p class="school-info"><strong>School: {{ school.username|index_format }} {{ school.first_name }}</strong></p>
	<table width="100%">
		<thead style="background: rgba(0, 0, 0, 0.5);">
			<th width="5%">SRL</th>
			{% if display_pp %}<th width="10%">Profile Picture</th>{% endif %}
			<th width="20%">Name<br>Father's Name</th>
			<th width="20%">Mother's Name<br>Guardian's Name</th>
			<th width="3%">S<br>X</th>
			<th width="3%">R<br>L</th>
			<th width="3%">C<br>C</th>
			<th width="7%">DOB</th>
			<th width="4%">FL</th>
			<th width="4%">SL</th>
			<th width="4%">OP EL</th>
			<th width="17%">Candidate's Signature</th>
		</thead>
		<tbody>
			{% for s in school.student_set.all %}
			<tr class="{% cycle 'white' 'gray' %}">
				<td>{{ s.serial }}{% if s.edited %}*{% endif %}</td>
				{% if display_pp %}<td>{% if s.profile_picture %}<img src="{{ s.profile_picture.url }}" />{% else %}No Image{% endif %}</td>{% endif %}
				<td>{{ s.name }}<br>{{ s.f_name }}</td>
				<td>{{ s.m_name }}<br>{{ s.get_guardian_name }}</td>
				<td>{% if s.sex == '1' %}M{% else %}F{% endif %}</td>
				<td>{{ s.religion }}</td>
				<td>{% if s.caste %}{{ s.caste }}{% endif %}</td>
				<td>{{ s.dob|date_format|date:'d/m/Y' }}<br>{% if s.underage_candidate %}(Underage){% endif %}</td>
				<td>{{ s.fl }}<br>{{ s.get_fl_short_code }}</td>
				<td>{{ s.sl }}<br>{{ s.get_sl_short_code }}</td>
				<td>{{ s.opt }}<br>{{ s.get_opt_el_short_code }}</td>
				<td>{% if not s.status == '1' %}Not Selected{% endif %}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<div class="bottom-box">
		<div class="declaration">
			<p class="verified_declaration">* Entire data has been verified by <span> {{ school.profile.verification_name }}</span>.</p>
			<p class="declaration_line"><strong>I, as the Head of the Institution, hereby declare that the above mentioned data of the Students of the school for registration of Class IX for the year 2023 prvoided by the West Bengal Board of Secondary Education is checked by the school.</strong></p>
		</div>
		<p class="signature"><strong>Signature of The Head of The Institution along with the seal</strong></p>
	</div>
	{% if school.profile.final_submitted_at %}
	<div class="report-date">
		<p>**The final submission of this school was done on {{ school.profile.final_submitted_at|date:'d/m/Y' }}.**</p>
	</div>
	{% endif %}
</body>
</html>

school/templates/school/profile.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
	.form-profile {
	    padding: 15px 35px 45px;
	    margin: 0 auto;
	    background-color: #fff;
	    border: 1px solid rgba(0, 0, 0, 0.1);
	}
	.wrapper {
	    margin-top: 50px;
	}
</style>
{% endblock %}
{% block content %}
<section class="bg-info" style="min-height: calc(100vh - 111px);">
	<div class="container-fluid mt-2">
		<div class="row align-items-center">
			<div class="col-md-6 offset-md-3">
				<div class="wrapper">
					<form class="form-profile" method="post" action="." >
						<h2 class="form-heading mb-4">Update Profile</h2>
						{% csrf_token %}
						{{ form.as_p }}
						<button class="btn btn-primary btn-block" type="submit">Save</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>	
{% endblock %}

school/templates/school/student_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block style %}
    <style>
        table th{
            vertical-align: middle !important;
            line-height: 1;
        }
    </style>
{% endblock %}
{% block content %}
<section class="bg-info" style="min-height: calc(100vh - 111px);">
    <div class="container-fluid">
        <div class="row justify-content-center pt-5">
            <div class=" col-sm-10 text-center">
                <p class="h2">
                    {{ userx.username }} <span> : {{userx.first_name}}</span><br>
                </p>
                <table class="table table-striped mb-0">
                    <thead>
                        <tr>
                            <th scope="col">Male</th>
                            <th scope="col">Female</th>
                            <th scope="col">Total</th>
                            <th scope="col">Verified & Selected<br><small>(For Issuance of Registration)</small></th>
                            <th scope="col">Verified & Not Selected<br><small>(For Issuance of Registration)</small></th>
                            <th scope="col">Pending</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td scope="row">{{male_students}}</td>
                            <td>{{female_students}}</td>
                            <td>{{total_students}}</td>
                            <td>{{selected_students}}</td>
                            <td>{{not_selected_students}}</td>
                            <td>{{pending_students}}</td>
                        </tr>
                    </tbody>
                </table>
                <div>
                    {% if first_student %}
                    <div class="text-center">
                        <a href="{{first_student.get_absolute_url }}" class="btn btn-success my-1">Start Editing Data</a>
                    </div>
                    {% endif %}
                    <table class="table table-striped table-dark">
                        <thead>
                            <tr>
                                <th scope="col">Serial</th>
                                <th scope="col">Name</th>
                                <th scope="col">Father's Name</th>
                                <th scope="col">Date of Birth</th>
                                <th scope="col">1st Language</th>
                                <th scope="col">2nd Language</th>
                                <th scope="col">Is Selected<br><small>(For Issuance of Registration)</small></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for s in page_obj %}
                            <tr>
                                <td scope="row"><a href="{{ s.get_absolute_url }}">{{s.serial}}</a></td>
                                <td>{{s.name}}</td>
                                <td>{{s.f_name}}</td>
                                <td>{{s.dob|date_format|date:'d/m/y'}}</td>
                                <td>{{s.get_fl_name}}</td>
                                <td>{{s.get_sl_name}}</td>
                                <td>{% if s.status == '1' %}Yes{% elif s.status == '2' %}No{% else %}-{% endif %}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% if not pending_students and not request.user.profile.complete %}
                    <div class="text-center">
                        <a href="{% url 'school:submit_final_data' %}" class="btn btn-success my-1">Submit Final Data</a>
                    </div>
                    {% endif %}
                    {% if not pending_students and request.user.profile.complete %}
                    <div class="text-center">
                        <a href="{% url 'school:pdf_report' %}" class="btn btn-success my-1">Download Report</a>
                    </div>
                    {% endif %}
                    <div class="container p-4">
                        <div class="pagination justify-content-center">
                            <span class="step-links">
                                {% if page_obj.has_previous %}
                                <a href="?page=1" class="bg-success text-white">&laquo; first</a>
                                <a href="?page={{ page_obj.previous_page_number }} " class="bg-danger text-white">previous</a>
                                {% endif %}
                                <span class="current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                                </span>
                                {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}" class="bg-danger text-white">next</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}" class="bg-success text-white">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block script %}
<script>
$('form').submit(function(e) {
    $(':disabled').each(function(e) {
        $(this).removeAttr('disabled');
    });
});
</script>
{% endblock %}

school/templates/school/submit-data.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
	.declaration{
		padding-top: 10px;
	}
	.declaration-box{
		border: 1px solid #dedede;
		padding: 10px 15px;
		color: rgba(0, 0, 0, 0.7);
	}
	form{
		margin-top: 15px;
	}
</style>
{% endblock %}
{% block content %}
<section class="declaration">
    <div class="container">
        <h2>Please read and agree to the following terms and conditions.</h2>
        <div class="declaration-box">
            The above mentioned data of the Students of the school for registration of Class IX for the year 2023 provided by the West Bengal Board of Secondary Education are checked by school. 
        </div>
        <form method="post" action=".">
        	{% csrf_token %}
        	<div class="form-group">
        		<div class="row">
	        		<div class="col-md-6">
			        	<label class="font-weight-bold" for="id_verification_name">Verifier's Name:</label>
			        	<input class="form-control" name="verification_name" id="id_verification_name" required="" placeholder="Please enter the name of the person who verified the data." />
			        </div>
			    </div>
	        </div>
        	<input type="checkbox" name="agree" id="id_agree" required="" />
        	<label for="id_agree">I agree to provide Admission Register and/or Birth Certificate and/or Caste Certificate (Original and/or Photocopy) whenever the Board asks for.</label>
        	<br><button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
</section>
{% endblock %}